services:
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - mailpit_network
networks:
    mailpit_network:
        driver: bridge
