services:
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: dockerdash_mailpit
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - dockerdash_mailpit
networks:
    dockerdash_mailpit:
        driver: bridge
