services:
  mariadb:
    image: mariadb:latest
    container_name: dockerdash_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
    ports:
      - "3306:3306"
    volumes:
      - dockerdash_mariadb:/var/lib/mysql

volumes:
  dockerdash_mariadb:
