services:
  mysql:
    image: mysql:latest
    container_name: dockerdash_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_pw
    ports:
      - "3307:3306"
    volumes:
      - dockerdash_mysql:/var/lib/mysql

volumes:
  dockerdash_mysql:
