services:
  postgres:
    image: postgres:latest
    container_name: dockerdash_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - dockerdash_postgres:/var/lib/postgresql/data

volumes:
  dockerdash_postgres: {}
